[project]
name = "lec2"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.6,<3.13"
numpy = ">=2.1.1,<2.2"
matplotlib = ">=3.9.2,<3.10"
pandas = ">=2.2.2,<2.3"
scipy = ">=1.14.1,<1.15"
jupyterlab = ">=4.2.5,<4.3"
